"""
Configuration for RAG Response Generation and Dialog Management Module
"""

import os

# Vector Database Configuration (from parent module)
VECTOR_DB_PATH = "../"
PINECONE_API_KEY = "pcsk_LPH9H_EJFoGtHEzGqGbRHg8tnu3ShsVfR9Si3ajinTHwBSh7r5ZDR5E8xPM3ubqszK5XL"
PINECONE_INDEX_NAME = "sri-lankan-legal-docs"
VECTOR_DIMENSION = 384

# LLM Configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "your-openai-api-key-here")
DEFAULT_MODEL = "gpt-3.5-turbo"
BACKUP_MODEL = "gpt-4"
MAX_TOKENS = 1000
TEMPERATURE = 0.3

# RAG Configuration
RETRIEVAL_TOP_K = 10
RERANK_TOP_K = 5
CONTEXT_WINDOW_SIZE = 4000
MIN_SIMILARITY_THRESHOLD = 0.5

# Response Generation Configuration
NUM_RESPONSE_VARIANTS = 3
RESPONSE_STYLES = ["professional", "detailed", "concise"]
MAX_RESPONSE_LENGTH = 800
MIN_RESPONSE_LENGTH = 100

# Dialog Management
MAX_CONVERSATION_HISTORY = 10
SESSION_TIMEOUT_MINUTES = 30
CONTEXT_RETENTION_TURNS = 5

# Legal Response Guidelines
LEGAL_DISCLAIMER = """
**Legal Disclaimer**: This response is generated by an AI system for informational purposes only. 
It should not be considered as legal advice. Please consult with a qualified legal professional 
for specific legal matters.
"""

UNCERTAINTY_PHRASES = [
    "Based on the available legal documents",
    "According to Sri Lankan legal precedents",
    "The legal framework suggests",
    "Legal authorities indicate",
    "From the retrieved legal sources"
]

CONFIDENCE_THRESHOLDS = {
    "high": 0.8,
    "medium": 0.6,
    "low": 0.4
}

# Frontend Configuration
FRONTEND_TITLE = "Sri Lankan Legal AI Assistant"
FRONTEND_SUBTITLE = "Powered by RAG Technology"
CHAT_PLACEHOLDER = "Ask your legal question here..."
MAX_CHAT_HISTORY_DISPLAY = 20

# Evaluation Configuration
RESPONSE_QUALITY_METRICS = [
    "relevance",
    "accuracy", 
    "completeness",
    "clarity",
    "legal_soundness"
]

# File Paths
CHAT_LOGS_DIR = "chat_logs"
EVALUATION_REPORTS_DIR = "evaluation_reports"
RESPONSE_CACHE_DIR = "response_cache"

# Create directories if they don't exist
for directory in [CHAT_LOGS_DIR, EVALUATION_REPORTS_DIR, RESPONSE_CACHE_DIR]:
    os.makedirs(directory, exist_ok=True)
